# syntax=docker/dockerfile:1

FROM golang:1.20

# Set destination for COPY
WORKDIR /app

# Download Go modules
COPY go-minitwit/go.mod go-minitwit/go.sum ./
RUN go mod download

COPY go-minitwit /app
COPY go-minitwit/templates /app/templates

# Install dockerize
ENV DOCKERIZE_VERSION v0.6.1
RUN wget --progress=dot:giga https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz


# Build
RUN go build -o /docker-gs-ping

EXPOSE 8081

ENV NAME World

# Run
CMD ["/docker-gs-ping"]
