version: '3'
services:
  web:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - ./data:/tmp # If you want to persist /tmp/minitwit.db outside the container
    command: >
      sh -c "python -c 'from minitwit import init_db; init_db()' &&
             python3 minitwit.py"
  db:
    image: postgres
    environment:
      POSTGRES_DB: minitwit
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data: