version: '3.3'

networks:
  main:

services:

  minitwitimage:
    image: ${DOCKER_USERNAME}/minitwitimage
    container_name: minitwit
    networks:
      - main
    depends_on:
      - itusqlimage
    ports:
        - '5000:5000'
    node:
      deploy:
        resources:
          limits:
            cpus: '0.001'
            memory: 2000M
          reservations:
            cpus: '0.0001'
            memory: 20M

  itusqlimage:
    image: ${DOCKER_USERNAME}/mysqlimage
    container_name: minitwit_mysql
    networks:
      - main
    ports:
      - '3306:3306'
    environment:
        - MYSQL_ROOT_PASSWORD=root
    node:
      deploy:
        resources:
          limits:
            cpus: '0.001'
            memory: 500m
          reservations:
            cpus: '0.0001'
            memory: 20M
