version: "3.8"

networks:
  itu-minitwit-network:
    external: false
    name: itu-minitwit-network

services:
  minitwitimage:
    #image: ${DOCKER_USERNAME}/minitwitimage
    image: local/minitwitimage

    container_name: minitwit
    env_file:
      - .env
    networks:
      - itu-minitwit-network
      #- itusqlimage
    depends_on:
      - grafana
      - prometheus
    ports:
      - "8081:8081"
    mem_limit: "1g"
    mem_reservation: "512m"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - itu-minitwit-network
    mem_limit: "1g"
    mem_reservation: "512m"

  grafana:
    image: grafana/grafana:10.2.4 
    ports:                        
      - "3000:3000"
    networks:                     
      - itu-minitwit-network
    mem_limit: "1g"
    mem_reservation: "512m"
    volumes:
      - grafana_data:/var/lib/grafana #to no get erased

  node_exporter:
    image: prom/node-exporter      
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - itu-minitwit-network

volumes:
  grafana_data: