version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NAME=World
    volumes:
      - ./templates:/app/templates
    mem_limit: "1g"
    mem_reservation: "512m"
