name: Create release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    name: Release new version
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Git identity
        run: |
          git config user.email "eduardostrindade@gmail.com"
          git config user.name "dudustri"

      - name: Create and push new tag based on the last one
        id: tag_release
        run: |
          tag_number=$(git tag -l | tac | grep -o '[0-9]\+' | awk '{print $1+1}' | head -n1)
          tag_name="Week${tag_number}"
          echo "$tag_number"
          echo "$tag_name"
          git tag -a $tag_name -m "DevOps - week ${tag_number} release"
          git push origin $tag_name

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          week_number=$(git tag -l | tac | grep -o '[0-9]\+' | head -n1)
          current_tag=$(git tag -l | tac | head -n1)
          echo "$week_number"
          echo "$current_tag"
          gh release create "${current_tag}" --repo="$GITHUB_REPOSITORY" --title="v${week_number}.0" --generate-notes
