name: minitwit CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  start_server_and_run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: checkout action
        uses: actions/checkout@v2

      - name: set go env
        uses: actions/setup-go@v2
        with:
          go-version: "1.21"

      - name: change the directory
        run: cd go-minitwit

      - name: install GO dependencies
        run: go mod tidy

      - name: install Python dependencies #maybe change it in the future to use a requirements file instead
        run: |
          pip install pytest
          pip install requests

      - name: start minitwit server
        run: go run *.go &

      - name: run pytest
        run: pytest go-minitwit/tests/
