name: minitwit CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  minitwit_server_test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout action
        uses: actions/checkout@v2

      - name: set go env
        uses: actions/setup-go@v2
        with:
          go-version: "1.21"

      - name: check ports before init
        run: netstat -tuln

      - name: Install dependencies and start minitwit server
        run: |
          cd go-minitwit
          go mod tidy
          go run *.go &
          sleep 60

      - name: check listening ports after init
        run: |
          netstat -tuln
          curl http://localhost:8081

      - name: set python env
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: install python dependencies #maybe change it in the future to use a requirements file instead
        run: |
          pip install pytest
          pip install requests

      - name: check listening ports
        run: |
          netstat -tuln
          curl http://localhost:8081

      - name: run pytest
        run: pytest go-minitwit/tests/
