name: minitwit CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  start_go_server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.21"

      - name: Install dependencies
        run: go mod tidy

      - name: Start Go server
        run: go run *.go &

  test_with_pytest:
    runs-on: ubuntu-latest

    needs: start_go_server

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install pytest
        run: pip install pytest

      - name: Install requests
        run: pip install requests

      - name: Run pytest tests
        run: pytest tests/
