name: Compile LATEX Report Pipeline

on:
  push:
    paths:
      - report/**

jobs: 
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: List files
        uses: ls
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: report/main.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: main.pdf
      - name: Push compiled report to repo
        run: |
          git config --global user.email "babkinedicapriotomas@gmail.com"
          git config --global user.name "Tomas Babkine-Di Caprio"
          cp ${{ github.workspace }}/main.pdf report/
          cd report
          git add main.pdf
          git commit -m "feat: add rendered latex"
          git push origin ${{ github.ref }}