name: Compile LATEX Report Pipeline

on:
  push:
    paths:
      - report/main.tex

jobs: 
  build_latex:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Checkout report branch
        run: git checkout report

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          working_directory: report/

      # - name: Upload PDF file
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: PDF
      #     path: main.pdf

      # - name: Download PDF file
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: PDF
      #     path: report/
      
      - name: Status
        run: git status

      - name: Add pdf file to version control
        run: git add .
      
      - name: Move file to report folder
        run: git mv main.pdf report/main.pdf -f

      - name: Delete artifacts generated by Latex compiler
        run: |
          rm main.aux
          rm main.fdb_latexmk
          rm main.fls
          rm main.log

      - name: Push compiled report to repo
        run: |
          git config --global user.email "babkinedicapriotomas@gmail.com"
          git config --global user.name "Tomas Babkine-Di Caprio"
          git add .
          git commit -m "feat: add rendered latex"
          git push origin ${{ github.ref }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Update report
          delete-branch: false