name: static_analysis_tools

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: 'false'

      # Install gofumpt
      - name: Install gofumpt
        run: go install mvdan.cc/gofumpt@latest

      # Use gofumpt instead of gofmt
      - name: Run gofumpt
        run: gofumpt -l -w .

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.54
          working-directory: ./go-minitwit

      - name: shellcheck
        run: |
          cd ./remote_files
          shellcheck deploy.sh

      - name: Hadolint (linter for the dockerfile)
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile-minitwit
